<?
$PERM["include"]["*"]="R";
$PERM["personal"]["*"]="R";
$PERM["auth"]["*"]="R";
$PERM["bitrix"]["*"]="R";
$PERM["products"]["*"]="R";
$PERM["press-center"]["*"]="R";
$PERM["partners"]["*"]="R";
$PERM["contacts"]["*"]="R";
$PERM["company"]["*"]="R";
$PERM["career"]["*"]="R";
$PERM["images"]["*"]="D";
$PERM["examples"]["*"]="D";
$PERM["e-store"]["*"]="D";
$PERM["content"]["*"]="D";
$PERM["communication"]["*"]="D";
$PERM["/"]["6"]="W";
$PERM["/"]["*"]="R";
?>